### ISSUE TITLE
Support for PostgreSQL / MySQL

### ISSUE THREAD

**Issue by gmemstr** [snikket-im/snikket-server#224]
Prosody supports PostgreSQL and MySQL for data storage, but Snikket does not - looking at https://github.com/snikket-im/snikket-server/blob/afd8ec36366b034816c37f78b7f665ac5a1147c5/ansible/files/prosody.cfg.lua#L242-L250, it should be fairly easy to add support, and I'm willing to put in the legwork if this is something that the project is okay with having supported.

**Comment by mwild1** [comment]
Hi, thanks for the feature request! I'm sorry I did not respond sooner - my internet has been down since last week (it's still down, but at least for now I have an alternative connection...). But anyway...

I'm afraid this is not something we are planning to support in Snikket. For a fully flexible server, we recommend using Prosody directly, which gets you support for many possible storage backends.

One of Snikket's design principles is to have a very minimal range of possible configurations. This allows us to test more thoroughly and keep upgrades simple and reliable for everyone. It also allows us more freedom to implement features if we keep everyone to a "narrow" configuration.

We are currently experimenting with SQLite for Snikket's storage. But if we decide to make it the default, this will not be optional - the current "internal" storage will be removed (after migration, of course). Switching over to SQLite would create [a lot of potential](https://github.com/snikket-im/snikket-server/issues/47), but if everyone is using different storage methods, it means we can't implement those features.

The phenomenon of multiple configuration options interacting with each other is related to the concept of [combinatorial explosion](https://en.wikipedia.org/wiki/Combinatorial_explosion#Computing).

> Note, however, that the combinatorics of only 216 simple Boolean features is comparable to the estimated number of atoms in the entire universe. With only 33 Boolean features, the combinatorics can represent one product for every human on the planet.
*[Charles W. Krueger. 2006. New Methods in Software Product Line Practice.
Commun. ACM 49, 12 (Dec. 2006), 37–40](https://cacm.acm.org/research/new-methods-in-software-product-line-practice/)*

Prosody has well over 300 configuration options out of the box, and many of those are more than just simple booleans. We have lots of automated tests, and lots of users testing our nightly builds, but inevitably when we push out a new Prosody release, there are always people who hit cases that were less tested or tested not at all. This reduces overall reliability, puts people off from upgrading, and increases the support burden.

We've been dealing with that the best we can for 15+ years of the Prosody project. It's fine. But for Snikket the goal is to make something even more robust and even lower maintenance, whether you're an experienced sysadmin or just starting out. Narrowing our configuration surface is one of the ways we achieve that. Prosody will always be available for situations where Snikket is too restrictive.

None of this is to say that that SQL, LDAP, or any of the other optional features from Prosody will *never* be supported in Snikket. We just don't want to rush into such a decision, despite the relative ease of "just" exposing those options.

I hope this is explanation is enough to compensate for the time you spent working on [the PR](https://github.com/snikket-im/snikket-server/pull/225) over the weekend. I'm really sorry I wasn't able to post this sooner, and I hope you understand the decision and rationale for why I will close it. I don't enjoy closing PRs, and I also hope it doesn't deter you from future contributions, should you feel the urge. Feel free to stop by the chatroom for discussion about any other ideas or feedback you have about Snikket. Cheers!
