### ISSUE TITLE
Suggestion: include xmpp address of snikket-admin in welcome message

### ISSUE THREAD

**Issue by aslmx** [snikket-im/snikket-server#31]
The welcome message currently includes the server admins email address. This is already good. 

But wouldn't it be useful to also include the admins xmpp URI in this welcome message? Maybe as a clickable link. Clickable link comes for free when adding the xmpp: URI scheme.

Same would be for email - but mailto: is currently not handled by snikket (or even upstream conversations)

Having this clickable link would reduce the barrier to contact the admin for questions by a lot.

I guess for the small instances this is anyway going to be the person who sent you the individual invite, but if there is e.g. a soccer club, this might get a bit more anonymous.

**Comment by mwild1** [comment]
Hi, thanks for submitting this idea! I've considered it, but it's not something I'm going to incorporate in the near future. My reasoning includes:

- The admin email address is already there (not being clickable is a shame, but a separate discussion).
- Snikket is aimed at small servers where you generally know the admin anyway (quite often it will be the admin that invites you).
- The email address can be useful in case of connectivity issues or status queries. The XMPP address is less useful in these cases.
- The admin is probably already on your contact list, since everyone is already subscribed to everyone else (unless you configure a circle, and then someone else may prefer to be the primary contact).
- For queries over XMPP there is also the group chat that you are placed into by default.

To help me keep the issue tracker focused on things I intend to think about or work on soon, I'm going to close this. Feel free to follow up if you have any further questions! :slightly_smiling_face:

**Comment by aslmx** [comment]
Thanks for your extensive reply. I see your point :)
