### ISSUE TITLE
Not able to create admin account - Invitation expired

### ISSUE THREAD

**Issue by kodxana** [snikket-im/snikket-server#43]
I installed server using docker and when I try to create admin account I get message about invitation expired.
```
docker exec snikket create-invite --admin --group default
```
Server is running behind haproxy reverse proxy.

**Comment by mwild1** [comment]
Hi, thanks for the report!

This message typically happens when the invite URL is not being proxied correctly. Ensure it includes any trailing characters shown by the create-invite command. Sometimes a `-` or `/` may get dropped by some software.

If you are unable to find the problem, some logs from the containers would be useful. You can run `docker-compose logs` to view them.

**Comment by kodxana** [comment]
Adress looks to be corect when I put it in browser

**Comment by kodxana** [comment]
I see that proxy container have issues
```
snikket-proxy     | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
snikket-proxy     | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
snikket-proxy     | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
```

**Comment by mwild1** [comment]
Please see this documentation for running Snikket behind a reverse proxy: https://github.com/snikket-im/snikket-server/blob/master/docs/advanced/reverse_proxy.md

**Comment by kodxana** [comment]
Now I'm stuck at 
```
Snikket is starting
We are currently obtaining SSL/TLS certificates to secure your Snikket service.
```

**Comment by mwild1** [comment]
For in-depth support issues, please join our community chat: https://snikket.org/contact/

**Comment by mwild1** [comment]
Hopefully you were able to resolve your issues in the chat! Closing this issue report.
