### ISSUE TITLE
Couldn't send message

### ISSUE THREAD

**Issue by vncloudsco** [snikket-im/snikket-server#63]
Dear Admin
Couldn't send message: Server-to-server connection failed: Could not authenticate to remote server, we get error can't send messages but only receive messages from other xmpp systems.

![image](https://user-images.githubusercontent.com/41409442/133572297-f376f4a6-6de7-477c-8366-6a7183b5fae6.png)

**Comment by vncloudsco** [comment]
This error is caused by missing DNS SRV records, how can I configure it?

**Comment by vncloudsco** [comment]
i have configured SRV records but they don't seem to work, i can't send messages to xmpp servers other than my network.
```
PS C:\Windows\system32> dig SRV _xmpp-client._tcp.mtz.pw

; <<>> DiG 9.14.2 <<>> SRV _xmpp-client._tcp.xxxxx.pw
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64607
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;_xmpp-client._tcp.xxxxx.pw.      IN      SRV

;; ANSWER SECTION:
_xmpp-client._tcp.xxxxx.pw. 300   IN      SRV     0 5 5222 xxxxx.pw.

;; Query time: 58 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Sep 16 17:22:09 SE Asia Standard Time 2021
;; MSG SIZE  rcvd: 79

```
refer to debugging.
https://prosody.im/doc/troubleshooting

**Comment by mwild1** [comment]
Hi, thanks for the report. Snikket servers do not need SRV records. Ensure you have the correct DNS records specified in the [installation guide](https://snikket.org/service/quickstart/).

Authentication problems can be caused by missing/invalid certificates, which can be caused by incorrect DNS. Again, double-check your setup. Good luck!

**Comment by m4teh** [comment]
This issue should not be closed. There is a problem with Snikket and outgoing communication.

`snikket.xx.com:saslauth           info	SASL EXTERNAL with hell.la failed: error<cancel:not-authorized:certificate not trusted>
s2sout564a5b8dbdd0                          info	Outgoing s2s stream snikket.xx.com->hell.la closed: error<cancel:not-authorized:certificate not trusted>
s2sout564a5b8dbdd0                          info	Sending error replies for 3 queued stanzas because of failed outgoing connection to hell.la  `


`snikket.xx.com:saslauth           info	SASL EXTERNAL with chat.xx.im failed: error<cancel:not-authorized:certificate has expired>
s2sout564a5b2778a0                          info	Outgoing s2s stream snikket.xx.com->chat.xx.im closed: error<cancel:not-authorized:certificate has expired>
s2sout564a5b2778a0                          info	Sending error replies for 1 queued stanzas because of failed outgoing connection to chat.xx.im`

All instances here using Let's Encrypt certs. Snikket can however receive messages from other instances but cannot send messages, sighting the same error as OP - "could not authenticate".

This is a new error and has appeared recently. We were using the default 'beta' branch on our primary instance, and I spun up a fresh new instance using 'dev' branch, with the exact same outcome.

We have migrated away from Snikket.

**Comment by mwild1** [comment]
The error in your paste suggests the remote server does not trust the certificate of your Snikket instance.

The remote domain in your sample is running ejabberd, and may be affected by the Let's Encrypt intermediate expiry. More info here: https://blog.windfluechter.net/2021/09/29/letsencrypt-ca-chain-issues-with-ejabberd/

There are many people using Snikket just fine to communicate with other servers, and I've had no reports of issues that can't be traced down to other causes. I'm happy to see evidence to the contrary, but based on the information you've provided, my suggestion above seems the most likely explanation.

Note that Snikket's behaviour in this case may differ to some other servers, because Snikket enforces certificate authentication for all server-to-server connections, while many deployments will fall back to an older DNS-based protocol called "dialback" if the TLS certificate is not trusted or cannot be verified. However Snikket intentionally has dialback disabled, and will only communicate with remote services where mutual trust based on TLS certificates can be established. TLS authentication is standard security practice in 2021.

Reopening this issue would be unhelpful with no further evidence. However right now there is nothing to go on, and you've migrated, so I think it is best left as-is unless someone can provide more details that show the existence of a bug.
