### ISSUE TITLE
HAProxy, own certbot, "Waiting for certificates..."

### ISSUE THREAD

**Issue by kirill-solovev** [snikket-im/snikket-server#92]
Good day,

I'm trying to run the docker image of Snikket, but it is stuck at 
```
snikket           | Waiting for certificates...
```
Is there any way to disable cert-monitor.sh or otherwise circumvent the check?
I have configured HAProxy to solve the acme challenges using a separate certbot + acme.sh container, so it's not quite compatible with Snikket's built-in solution.
I received certificates for the following 3 domains:
1. `groups.snikket.<myserver>`
2. `share.snikket.<myserver>`
3. `snikket.<myserver>`

and tried pointing the container to the appropriate directory:
```
...
snikket_server:
...
  volumes:
    - <path_to_my_certs>:/etc/ssl/certbot
```
Yet it doesn't seem to help.

**Comment by mwild1** [comment]
Hi, thanks for the report.

Snikket requires certificates because it offers non-HTTPS services that use TLS (e.g. XMPP, TURN) and these protocols typically cannot be tunnelled through reverse proxies, which is why a reverse proxy that automatically obtains certificates for HTTPS is an incomplete solution.

If you have certificates available outside of Snikket for the required domains **and** the directory structure matches the one that certbot uses (`live/<domain>/cert.pem`) you can mount them as volumes:

```
volumes:
  - /path/to/letsencrypt:/snikket/letsencrypt
```

This mount would need to be added into both the snikket-web-proxy and snikket-server containers. You should also disable the snikket-cert-manager container if you do this.

We are hoping to increase compatibility with different directory structures for certificates in an upcoming release.

The easiest solution is generally to just ensure unrecognised HTTP challenge requests from Let's Encrypt are proxied through to Snikket, so it can obtain its own certificates. This does not prevent your reverse proxy from also obtaining certificates for the same domain.

Alternatively you can just disable the automatic certificate generation in the reverse proxy, and pass through encrypted connections as TCP (haproxy supports SNI if you need to route to multiple domains/services on the same port 443).

Reverse proxies can be a pain to get right, and everyone has a different setup, which is why it's difficult to give accurate general advice. If you get your setup working, please consider contributing to the documentation at https://github.com/snikket-im/snikket-server/blob/master/docs/advanced/reverse_proxy.md

Good luck!

(I will close this issue as there is no direct bug report and it's not a development task, but feel free to continue to post updates or discuss your progress in the [community chat](https://snikket.org/contact/)).
