### ISSUE TITLE
Q: Do Audio/Video calls use direct connection after STUN/TURN?

### ISSUE THREAD

**Issue by xcme** [snikket-im/snikket-server#97]
Hi guys,

Sorry for that "issue spam", just want to ask where I can read about calls logic that Snikket use. I took a look at the explanation what STUN is and checked connection flow between two nodes. Do I understand it right, that a couple of Snikket applications uses my own server in order to find theirs public IPs and establish direct connection after that? So, the traffic doesn't flow through my or your server, correct?

What would happen if they couldn't find any option to establish direct connection? Would them use my server as proxy then?

I'd appreciate if you can say a couple of words in regards to the audio/video calls logic. Couldn't find it in docs directory on github.

Thanks.

**Comment by xcme** [comment]
I used such a setup and seems that traffic flows from one **private** IP to other **private** IP without being leaving the upper router towards to Internet:
![image](https://user-images.githubusercontent.com/10675508/146808764-f78ae793-8f0b-4169-be55-bd9c7f87fe12.png)

**Comment by mwild1** [comment]
> I'd appreciate if you can say a couple of words in regards to the audio/video calls logic. Couldn't find it in docs directory on github.

It's complicated!

Snikket uses WebRTC, which uses ICE, which uses STUN and TURN. Lots of protocols and algorithms interact in various ways, and a lot of modern audio/video transmission online is built on this stack.

I'll attempt to provide a rough description of the process. When you call someone, or answer a call from them, the clients of both sides exchange a list of their IP addresses. They then try to establish to each other using the IP addresses they've been given. If both parties are on the same network, using the private IP addresses will work (and be preferred). In many cases, a client might be behind a NAT, and it can use STUN to discover its external IP address. Combined with NAT "hole punching" techniques, it can often establish a direct connection with a peer even through most NATs. In some cases, such as when both parties are behind restrictive NATs, the connection ends up relayed through a TURN server. This is always the last resort, because it consumes server bandwidth and generally introduces additional latency. But without TURN, some calls would be unable to connect.

If you self-host Snikket, it includes a TURN server, and will use that by default when necessary. If you use Snikket hosting, we provide a TURN server for you (actually we have two, one in Europe and one in North America, to reduce latency according to your region).

As all calls in Snikket are encrypted, the TURN server will only see encrypted traffic flowing through it, and is unable to access the audio/video streams.

But again, TURN is a last resort. The goal is always to find the best path to the other device, and if they are both on the same network and can communicate directly, the data never needs to leave the network.

I hope this helps!

**Comment by xcme** [comment]
Thanks for the explanation!
